language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=sphinx06
    - TOXENV=sphinx10
    - TOXENV=sphinx11
    - TOXENV=sphinx12
    - TOXENV=coverage
install: pip install -U pip setuptools docutils tox
script: tox
